#!/bin/sh
#
# build the package in a docker image
#

#*  parameters
#
PATH=/usr/local/bin:/bin:/usr/bin
export PATH

test "$TRACE" && set -x

BASE=uni-json-base
BUILD=uni-json

USR=`id -un`
BASE_IMG="$USR/$BASE"
BUILD_IMG="$USR/$BUILD"

#*  functions
#
have_img()
{
    docker image ls "$1" --format a | grep -q .
}

#*  main
#
have_img "$BASE_IMG" || \
    docker image build -t "$BASE_IMG" - <docker/$BASE.dockerfile

have_img "$BUILD_IMG" && {
    for x in `docker container ls -aqf "ancestor=$BUILD_IMG"`;
    do
        printf 'removing %s\n' "$x" >&2
        docker container rm $x
    done

    docker image rm "$BUILD_IMG"
}

docker build -t "$BUILD_IMG" -f docker/$BUILD.dockerfile --build-arg "img=$BASE_IMG" .
docket container run -v `pwd`/tmp:/tmp/out "$BUILD_IMG" /tmp/uni-json/scripts/do-docker-build
