#!/bin/sh
#
# build the package in a docker image
#

#*  parameters
#
PATH=/usr/local/bin:/bin:/usr/bin
export PATH

test "$TRACE" && set -x

BASE=uni-json-base
BUILD=uni-json

#*  functions
#
have_img()
{
    docker image ls "$1" --format a | grep -q .
}

#*  main
#
have_img "$BASE" || \
    docker image build -t "$BASE" - <docker/$BASE.dockerfile

have_img "$BUILD" && {
    for x in `docker container ls -aqf ancestor=$BUILD`;
    do
        printf 'removing %s\n' "$x" >&2
        docker container rm $x
    done

    docker image rm "$BUILD"
}
